[phases.setup]
nixPkgs = ["nodejs_22"]
nixpkgsArchive = "ba913eda2df8eb72147259189d55932012df6301"

[phases.install]
cmds = [
  "cd backend",
  "npm ci --only=production"
]

[phases.build]
cmds = [
  "cd backend",
  "npm run build"
]

[start]
cmd = "cd backend && node dist/index.js"

[variables]
NODE_VERSION = "22"
NODE_ENV = "production"
